In [7]:
import pandas as pd 
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [4]:
## Creating sentimental polarity 
analyzer = SentimentIntensityAnalyzer()
def compound_score(txt):
    return analyzer.polarity_scores(txt)["compound"]

## Sentiments
def sentiment(score):
    emotion = ""
    if score >= 0.5:
        emotion = "Positive"
    elif score <= -0.5:
        emotion = "Negative"
    else:
        emotion = "Neutral"
    return emotion

In [8]:
## Importing CSV file
df = pd.read_csv("tripadvisor_hotel_reviews.csv", encoding = "ISO-8859-1")

## Applying Compund score
polarity_scores = df["Review"].astype("str").apply(compound_score)
df["Sentiment_Score"] = polarity_scores

## Applying Sentiment
df["Sentiment"] = df["Sentiment_Score"].apply(sentiment)

In [4]:
## Saving preprocessed file 
df.to_csv("Tripadvisor_hotel_reviews-rating-sentiments.csv",index=False)
df.Sentiment.value_counts()

Positive    18319
Negative     1090
Neutral      1082
Name: Sentiment, dtype: int64

In [9]:
# Importing the Trip-Advisor-Hotel-Review Dataset
data = pd.read_csv('Tripadvisor_hotel_reviews-rating-sentiments.csv')

# Having a look at the data
data.head(20)

,Review,Rating,Sentiment_Score,Sentiment
0,nice hotel expensive parking got good deal sta...,4,0.9626,Positive
1,ok nothing special charge diamond member hilto...,2,0.9870,Positive
2,nice rooms not 4* experience hotel monaco seat...,3,0.9842,Positive
3,"unique, great stay, wonderful time hotel monac...",5,0.9920,Positive
4,"great stay great stay, went seahawk game aweso...",5,0.9870,Positive
5,love monaco staff husband stayed hotel crazy w...,5,0.9870,Positive
6,"cozy stay rainy city, husband spent 7 nights m...",5,0.9927,Positive
7,"excellent staff, housekeeping quality hotel ch...",4,0.9590,Positive
8,"hotel stayed hotel monaco cruise, rooms genero...",5,0.9618,Positive
9,excellent stayed hotel monaco past w/e delight...,5,0.9756,Positive
10,"poor value stayed monaco seattle july, nice ho...",2,0.9666,Positive
11,nice value seattle stayed 4 nights late 2007. ...,4,0.9242,Positive
12,nice hotel good location hotel kimpton design ...,4,0.9859,Positive
13,nice hotel not nice staff hotel lovely staff q...,3,-0.0984,Neutral
14,"great hotel night quick business trip, loved l...",4,0.9608,Positive
15,horrible customer service hotel stay february ...,1,0.4700,Neutral
16,disappointed say anticipating stay hotel monac...,2,0.9846,Positive
17,fantastic stay monaco seattle hotel monaco hol...,5,0.9957,Positive
18,"good choice hotel recommended sister, great lo...",5,0.9300,Positive
19,hmmmmm say really high hopes hotel monaco chos...,3,0.9891,Positive